### ISSUE TITLE
killcounter is wrong

### ISSUE THREAD

**Issue by nomisum** [gruppe-adler/TvT_Template.VR#10]
probably twice the number actually killed

**Comment by McDiod** [comment]
Displays the actual points instead of kills:
https://github.com/gruppe-adler/TvT_RoterStern.lythium/blob/master/USER/points.hpp#L14

This has always been a cause for confusion though. Should probably change it to say "points for player kills" or something.

**Comment by nomisum** [comment]
oh well, seems i forgot to change that value to 120 🙄
