### ISSUE TITLE
Vorbereitungszeit außerhalb Bildschirm auf 4K

### ISSUE THREAD

**Issue by McDiod** [gruppe-adler/TvT_Template.VR#21]

**Comment by nomisum** [comment]
![20181203204511_1](https://user-images.githubusercontent.com/500164/49404478-db635f80-f74f-11e8-90d7-c6178bab37a9.jpg)

**Comment by McDiod** [comment]
Teste mal `TvT_Template_uiscaleTest1.VR` bitte. Ist auf dem Server.

```sqf
[5] call grad_missionSetup_fnc_startPreparationTime
```

**Comment by nomisum** [comment]
klappt

![20181208195413_1](https://user-images.githubusercontent.com/500164/49689565-22bc6800-fb23-11e8-9125-33ff7cc7ee5c.jpg)
